name: Floppa Staging CD

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref }}
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Checkstyle
        run: mvn checkstyle::check

      - name: Compile with Maven
        run: mvn compile

      - name: Unit tests
        run: mvn test -Dtest=glo2003/unit/*
        env:
          MONGO_CONNECTION: ${{secrets.MONGO_LOCAL}}
          MODE: STAGING

      - name: System tests
        run: mvn test -Dtest=glo2003/e2e/*
        env:
          MONGO_CONNECTION: ${{secrets.MONGO_LOCAL}}
          MODE: STAGING

      - name: Code Coverage
        run: mvn jacoco:report

      - name: Code Quality Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          sonar.branch.name: origin/dev
          sonar.branch.target: origin/dev
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bonne_question -Pcoverage

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Deploy with Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "staging-bonne-question"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          delay: 5
          healthcheck: "https://staging-bonne-question.herokuapp.com/health"
          rollbackonhealthcheckfailed: true

        env:
          HD_MONGO_CONNECTION: ${{secrets.MONGO_CONNECTION}}
          HD_MODE: STAGING

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}