name: Java CI Maven
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Format style
        run: mvn git-code-format:format-code -Dgcf.globPattern=**/*

      - name: Validate style
        run: mvn git-code-format:validate-code-format -Dgcf.globPattern=**/*

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Compile with Maven
        run: mvn compile

      - name: Tests
        run: mvn test

      - name: Integration tests
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Formatting auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic formatting
