name: Java CI Maven
on:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          
      - name: Checkstyle
        run: mvn checkstyle::check

      - name: Compile with Maven
        run: mvn compile

      - name: Unit tests
        run: mvn test -Dtest=glo2003/unit/*

      - name: System tests
        run: mvn test -Dtest=glo2003/e2e/*
